### ISSUE TITLE
Error: Unable to fetch video metadata from youtube

### ISSUE THREAD

**Issue by ucalyptus** [efossier/youtube-mp3#4]
```

(base) ✕ [ucalyptus@ucalyptus ~/youtube-mp3 ] ➜ nvm run 8.0.0 youtube-mp3.js https://www.youtube.com/watch\?v\=1H1TL0jD1vw                                    
Running node v8.0.0 (npm v5.0.0)

__  __             __          __             __              __  ___   ___    ____
\ \/ / ___  __ __ / /_ __ __  / /  ___       / /_ ___        /  |/  /  / _ \  |_  /
 \  / / _ \/ // // __// // / / _ \/ -_)     / __// _ \      / /|_/ /  / ___/ _/_ < 
 /_/  \___/\_,_/ \__/ \_,_/ /_.__/\__/      \__/ \___/     /_/  /_/  /_/    /____/ 

                                      (1.2.6)


ERROR: Unable to fetch video metadata from youtube.
Error: Error parsing config: Unexpected token ; in JSON at position 289498
    at gotConfig (/home/ucalyptus/youtube-mp3/node_modules/ytdl-core/lib/info.js:123:21)
    at request (/home/ucalyptus/youtube-mp3/node_modules/ytdl-core/lib/info.js:74:7)
    at PassThrough.Miniget.stream.on (/home/ucalyptus/youtube-mp3/node_modules/miniget/dist/index.js:215:32)
    at emitNone (events.js:110:20)
    at PassThrough.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
(base) ✕ [ucalyptus@ucalyptus ~/youtube-mp3 ] ➜ 

```

**Comment by ucalyptus** [comment]
Updating ytdl to latest and then reinstalling this repo helped.
